#pragma once
#include <Windows.h>
#include "../libs/TinyECDH/ecdh.h"

//-- Global variables
BYTE CHACHA20KEY_1[88];
BYTE CHACHA20KEY_2[44];

BYTE CHACHA20_FINAL_KEY_1[32];
BYTE CHACHA20_FINAL_KEY_2[32];

BYTE CHACHA20NONCE_1[12];
BYTE CHACHA20NONCE_2[12];

BYTE CHACHA20_FINAL_NONCE[12];

BYTE VICTIM_ECDH_PUBLIC_KEY[ECC_PUB_KEY_SIZE];
BYTE VICTIM_ECDH_PRIVATE_KEY[ECC_PRV_KEY_SIZE];

BYTE ECDH_SHARED_SECRET[ECC_PUB_KEY_SIZE];